### ISSUE TITLE
Panic on empty interface{} type

### ISSUE THREAD

**Issue by tejasmanohar** [segmentio/glue#13]
We can't support interfaces with actual methods since they're not encodable obviously... but we should support the empty `interface{}` type (Go's "any" value).

```
panic: unexpected type: *types.Interface

goroutine 1012 [running]:
github.com/segmentio/glue/provider/internal.GetTypeInfo(0x148f880, 0xc4326e8e10, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/tejas/dev/src/github.com/segmentio/glue/provider/internal/types.go:98 +0x4d7
github.com/segmentio/glue/provider/internal.GetTypeInfo(0x148f8c0, 0xc4259002c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/tejas/dev/src/github.com/segmentio/glue/provider/internal/types.go:91 +0x566
github.com/segmentio/glue/provider/internal.GetTypeInfo(0x148f940, 0xc432665fd0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/tejas/dev/src/github.com/segmentio/glue/provider/internal/types.go:66 +0xd15
github.com/segmentio/glue/provider/stl.(*Provider).GetArgType(0x14c8b00, 0xc431be5310, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/tejas/dev/src/github.com/segmentio/glue/provider/stl/stl.go:67 +0xac
github.com/segmentio/glue/provider/gorilla.(*Provider).GetArgType(0xc420012a80, 0xc4326e81e0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/tejas/dev/src/github.com/segmentio/glue/provider/gorilla/gorilla.go:31 +0x95
github.com/segmentio/glue.(*Generator).Generate(0xc42a173de0, 0x12e574b, 0x6, 0x7fff5fbff99c, 0x9, 0xc429fc5880, 0xa, 0x10, 0x0, 0x0, ...)
	/Users/tejas/dev/src/github.com/segmentio/glue/generator.go:64 +0x171
github.com/segmentio/glue.(*Walker).walkPackage(0xc42000a840, 0xc420084840, 0x7fff5fbff984, 0xe, 0x7fff5fbff99c, 0x9, 0x0, 0x0)
	/Users/tejas/dev/src/github.com/segmentio/glue/walker.go:79 +0x543
github.com/segmentio/glue.(*Walker).Walk.func1(0xc431f1e9e0, 0xc42000a840, 0x12e3bd5, 0x1, 0x7fff5fbff984, 0xe, 0x7fff5fbff99c, 0x9, 0xc420084840)
	/Users/tejas/dev/src/github.com/segmentio/glue/walker.go:48 +0x90
created by github.com/segmentio/glue.(*Walker).Walk
	/Users/tejas/dev/src/github.com/segmentio/glue/walker.go:49 +0x195
```

**Comment by tejasmanohar** [comment]
https://github.com/segmentio/glue/pull/14
